const baseUrl = "https://norma.nomoreparties.space/api";
const INITIAL_DATA_REQUEST = "INITIAL_DATA_REQUEST";
const INITIAL_DATA_REQUEST_SUCCESS = "INITIAL_DATA_REQUEST_SUCCESS";
const INITIAL_DATA_REQUEST_FAILED = "INITIAL_DATA_REQUEST_FAILED";
const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
const POST_ORDER_REQUEST_SUCCESS = "POST_ORDER_REQUEST_SUCCESS";
const POST_ORDER_REQUEST_FAILED = "POST_ORDER_REQUEST_FAILED";

export {
    baseUrl, 
    INITIAL_DATA_REQUEST, INITIAL_DATA_REQUEST_SUCCESS,
    INITIAL_DATA_REQUEST_FAILED, 
    POST_ORDER_REQUEST, 
    POST_ORDER_REQUEST_SUCCESS, 
    POST_ORDER_REQUEST_FAILED 
};