const baseUrl = "https://norma.nomoreparties.space/api";

const INITIAL_DATA_REQUEST = "INITIAL_DATA_REQUEST";
const INITIAL_DATA_REQUEST_SUCCESS = "INITIAL_DATA_REQUEST_SUCCESS";
const INITIAL_DATA_REQUEST_FAILED = "INITIAL_DATA_REQUEST_FAILED";

const POST_ORDER_REQUEST = "POST_ORDER_REQUEST";
const POST_ORDER_REQUEST_SUCCESS = "POST_ORDER_REQUEST_SUCCESS";
const POST_ORDER_REQUEST_FAILED = "POST_ORDER_REQUEST_FAILED";

const SET_BUNS = "SET_BUNS";
const SET_SAUCES = "SET_SAUCES";
const SET_FILLINGS = "SET_FILLINGS";
const SET_INITIAL_DATA_TO_INGRIDIENTS = "SET_INITIAL_DATA_TO_INGRIDIENTS";

const ItemTypes={
    INGRIDIENT: "ingridient",
    CONSTRUCTOR_INGRIDIENT: "constructorIngridient",
}

const ADD_TO_CONSTRUCTOR = "ADD_TO_CONSTRUCTOR";
const DELETE_FROM_CONSTRUCTOR = "DELETE_FROM_CONSTRUCTOR";
const RENDER_INGRIDIENTS = "RENDER_INGRIDIENTS";


export {
    baseUrl, 
    
    INITIAL_DATA_REQUEST, 
    INITIAL_DATA_REQUEST_SUCCESS,
    INITIAL_DATA_REQUEST_FAILED, 

    POST_ORDER_REQUEST, 
    POST_ORDER_REQUEST_SUCCESS, 
    POST_ORDER_REQUEST_FAILED,

    SET_INITIAL_DATA_TO_INGRIDIENTS,
    SET_BUNS,
    SET_SAUCES,
    SET_FILLINGS,

    ItemTypes,

    ADD_TO_CONSTRUCTOR,
    DELETE_FROM_CONSTRUCTOR,
    RENDER_INGRIDIENTS,

};