const INGRIDIENTS_MODAL_ACTIVE = "INGRIDIENTS_MODAL_ACTIVE";
const INGRIDIENTS_MODAL_DISABLED = "INGRIDIENTS_MODAL_DISABLED";
const ORDER_MODAL_ACTIVE = "ORDER_MODAL_ACTIVE,"
const ORDER_MODAL_DISABLED = "ORDER_MODAL_DISABLED,"

export {
    INGRIDIENTS_MODAL_ACTIVE,
    INGRIDIENTS_MODAL_DISABLED,
    ORDER_MODAL_ACTIVE,
    ORDER_MODAL_DISABLED,
};
